import "~/styles/globals.css";
import { ClerkProvider} from '@clerk/nextjs';
import Topnav from "~/app/_components/topnav";

import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "gallery app",
  description: "Generated by Cheikh Sadibou SIDIBE",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={`font-sans ${inter.variable} flex flex-col gap-4`}>
        <Topnav />
        {children}</body>
    </html>
    </ClerkProvider>
  );
}
